name: ei_positive_affirmations
description: EI Positive Affirmations


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^0.3.3
  record: ^4.1.1
  path_provider: ^2.0.10
  audioplayers: ^0.20.1
  rive: ^0.8.4
  font_awesome_flutter: ^10.1.0
  percent_indicator: ^4.0.1
  smooth_page_indicator: ^1.0.0+2
  lottie: ^1.3.0
  on_audio_query: ^2.6.1
  sqflite:




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - rive/
    - images/
    - lottie/
  fonts:
    - family: Rubik
      fonts:
        - asset: Fonts/Rubik-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700